<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Belt_and_Gripper" Id="{9ead365b-d204-4444-b5a5-da437d7e747f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Belt_and_Gripper
VAR
	STATUS : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF STATUS = TRUE THEN
	;
END_IF]]></ST>
    </Implementation>
    <LineIds Name="Belt_and_Gripper">
      <LineId Id="5" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>