<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Handling" Id="{664ad419-ffd5-4bb9-a60b-af473f9c044f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Handling
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Handling">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>