<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PickandPlace" Id="{bf1217fb-f291-4d9f-ad63-4b91b16f2452}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PickandPlace
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PickandPlace">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>