<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Separating" Id="{32e5b463-f3c1-4022-8d80-bede1943fbe5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Separating
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Separating">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>